//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: nkbb Created :
// Initializer: nkbb.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "nkbbFunctionMap.h"
#include  <XSModelFunction.h>

extern "C" int Nkbb_Init(Tcl_Interp* tclInterp);
extern "C" int Nkbb_SafeInit(Tcl_Interp* tclInterp);

int Nkbb_Init(Tcl_Interp* tclInterp)
{
        return Nkbb_SafeInit(tclInterp);
}

int Nkbb_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "nkbb";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createnkbbFunctionMap();
        XSModelFunction::updateComponentList
              ("/opt/tools/nkbb_frin/lmodel_nkbb.dat");
        return TCL_OK;

}

